name: Build Android APK

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # >>> مهم: جاوا 17
      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip python3-pip libffi-dev libssl-dev build-essential

      - name: Install Android cmdline tools & SDK
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        shell: bash
        run: |
          set -e
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdtools.zip
          unzip -q cmdtools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
          mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          mkdir -p "$HOME/.android" && touch "$HOME/.android/repositories.cfg"
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;25.2.9519653"

      - name: Install buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install cython buildozer

      - name: Build APK (debug)
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
          ANDROIDSDK: ${{ github.workspace }}/android-sdk
          ANDROIDNDK: ${{ github.workspace }}/android-sdk/ndk/25.2.9519653
          PATH: ${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/build-tools/34.0.0:${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ env.PATH }}
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
