name: Build Android APK

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      BUILD_TOOLS_VER: "34.0.0"
      ANDROID_API: "34"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: System deps
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv git unzip zip libffi-dev libssl-dev build-essential

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "cython<3" buildozer

      - name: Install Android cmdline-tools + SDK packages
        run: |
          set -e
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT/cmdline-tools"
          # دانلود cmdline-tools
          curl -sSL -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdtools.zip
          rm -f cmdtools.zip
          mv cmdline-tools latest
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
          # نصب پکیج‌ها + پذیرش لایسنس‌ها
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-${ANDROID_API}" "build-tools;${BUILD_TOOLS_VER}"
          sdkmanager --list | head -n 50
          echo "PATH پس از نصب:"
          echo "$PATH"

      - name: Build APK (debug)
        env:
          ANDROIDSDK: ${{ github.workspace }}/android-sdk
        run: |
          export PATH="$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/${BUILD_TOOLS_VER}:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
