name: Build Android APK

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: System deps
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv openjdk-17-jdk unzip git libffi-dev libssl-dev build-essential
          python3 -m pip install --upgrade pip

      - name: Install buildozer
        run: |
          python3 -m pip install cython buildozer==1.5.0

      - name: Build (debug)
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: arbtracker-apk
          path: bin/*.apk
