name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROIDSDK: /usr/local/lib/android/sdk
      ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk-bundle
      ANDROIDNDK: /usr/local/lib/android/sdk/ndk-bundle
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk unzip curl git \
                                  libffi-dev libssl-dev zlib1g-dev libbz2-dev libsqlite3-dev
          python3 -m pip install --upgrade pip
          python3 -m pip install cython buildozer

      - name: Install Android cmdline-tools (sdkmanager)
        run: |
          set -e
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          if [ ! -x "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
            curl -L -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
            unzip -q cmdtools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
            mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          fi

      - name: Accept licenses & install SDK/NDK packages
        run: |
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses || true
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
            "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"
          # جابجایی NDK به مسیر استانداردی که پ4ا/بیلدوزر می‌شناسند
          mv "$ANDROID_SDK_ROOT/ndk/25.2.9519653" "$ANDROID_SDK_ROOT/ndk-bundle"

      - name: Force Buildozer to use external SDK/NDK (symlinks)
        run: |
          mkdir -p /home/runner/.buildozer/android/platform
          ln -sfn "$ANDROID_SDK_ROOT" /home/runner/.buildozer/android/platform/android-sdk
          ln -sfn "$ANDROID_SDK_ROOT/ndk-bundle" /home/runner/.buildozer/android/platform/android-ndk
          # چک سریع برای وجود aidl در build-tools
          ls -l "$ANDROID_SDK_ROOT/build-tools/33.0.2/aidl"

      - name: Build APK (debug)
        run: |
          echo "SDK -> $(readlink -f /home/runner/.buildozer/android/platform/android-sdk)"
          echo "NDK -> $(readlink -f /home/runner/.buildozer/android/platform/android-ndk)"
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
